services:
  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:latest
      restart: always
      env_file: .env
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
        KC_DB_USER: keycloak
        KC_DB_SCHEMA: public
        KC_DB_PASSWORD: ${KC_DB_PASSWORD}
        KC_HOSTNAME: ${KC_HOSTNAME}
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
        KC_PROXY: edge
        # TODO: add PEM with certbot?
        #REF: https://www.keycloak.org/server/keycloak-truststore
        # KC_TRUSTSTORE_PATHS: /path/of/some.pem,/dir/contain/pems/
      # ports:
        # - 8080:8080
      volumes:
        # Override default config
        # - ./keycloack.conf:${CWD}/conf/keycloack.conf
      depends_on:
        - keycloak-db
      networks:
        - reverseproxy-nw
        - keycloak-nw
      command: 
        # - --config-file=/path/to/myconfig.conf
        - start
        #- --truststore-paths=/opt/truststore/myTrustStore.pfx,/opt/other-truststore/myOtherTrustStore.pem

  keycloak-db:
      container_name: keycloak-db
      image: postgres:latest
      restart: always
      security_opt:
        - label:disable
      volumes:
        - ./container-data/db:/var/lib/postgresql/data
        - /etc/localtime:/etc/localtime:ro
      env_file: .env
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    #   ports:
        # - 5432:5432
      networks:
        - keycloak-nw

networks:
    keycloak-nw:
    reverseproxy-nw:
        external: true
