
# REF: https://github.com/tiredofit/docker-discourse/blob/main/examples/docker-compose.yml

services:
  discourse-app:
    container_name: discourse-app
    image: tiredofit/discourse:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.discourse-example-org.rule=Host(`${DISCOURSE_HOST_NAME}`)
      - traefik.http.services.discourse-example-org.loadbalancer.server.port=3000
    volumes:
    # https://github.com/tiredofit/docker-discourse/tree/main?tab=readme-ov-file#persistent-storage
      - ./logs:/data/logs
      - ./data/uploads:/data/uploads
      - ./data/backups:/data/backups
      - ./data/plugins:/data/plugins
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-app

      - DB_HOST=discourse-db
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password

      - REDIS_HOST=discourse-redis
      - SITE_HOSTNAME=${DISCOURSE_HOST_NAME}

      - SMTP_PORT=25
      - SMTP_HOST=postfix-relay

      - DEVELOPER_EMAILS=hostmaster@example.com
    restart: always
    networks:
      - proxy
      - discourse-backend

  discourse-db:
    container_name: discourse-db
    image: tiredofit/postgres:15-latest
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-db

      - POSTGRES_DB=discourse
      - POSTGRES_USER=discourse
      - POSTGRES_PASSWORD=password
    networks:
      - discourse-backend

  discourse-redis:
    image: tiredofit/redis:7
    container_name: discourse-example-org-redis
    volumes:
      - ./redis:/var/lib/redis
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-redis
    networks:
      - discourse-backend
    restart: always

  discourse-db-backup:
    image: tiredofit/db-backup
    container_name: discourse-db-backup
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-db-backup
      - DB_HOST=discourse-db
      - DB_TYPE=postgres
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
    networks:
      - discourse-backend
    restart: always


networks:
  proxy:
    external: true
  discourse-backend:
    # external: true
